# Generated by Django 6.1.1 on 2026-09-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentverification',
            name='bank',
            field=models.CharField(choices=[('cbe', 'Commercial Bank of Ethiopia'), ('telebirr', 'Telebirr')], db_index=True, default='cbe', max_length=20),
        ),
    ]
