# Generated by Django 6.1.1 on 2026-09-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentverification_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentverification',
            name='receiver_verified',
            field=models.BooleanField(default=False),
        ),
    ]
